version: '3'

services:
  django:
    build: 
      context: .
      target: django-app
    restart: always
    env_file: .env
    expose:
      - 8000
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/staticfiles

volumes:
  media:
  static:
      