# Generated by Django 3.2.15 on 2024-01-09 12:27

from django.db import migrations
from django.db.models import Subquery, OuterRef, F


def calc_order_item_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')

    OrderItem.objects.all().update(
        price=Subquery(OrderItem.objects.filter(pk=OuterRef('pk'))
                       .values('product__price')[:1])*F('quantity')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(calc_order_item_price)
    ]
