# Generated by Django 3.2.15 on 2024-01-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20240113_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('10_N', 'New'), ('20_C', 'Check data'), ('30_M', 'Cook and pack'), ('40_D', 'Delivering'), ('50_F', 'Finished')], db_index=True, default='10_N', max_length=5, verbose_name='статус'),
        ),
    ]
