# Generated by Django 3.2.15 on 2024-01-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20240118_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('D', 'Наличными при доставке'), ('B', 'Накопленными бонусами/скидками'), ('O', 'Картой онлайн')], db_index=True, max_length=2, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('10_N', 'New'), ('20_C', 'Check data'), ('30_M', 'Cook and pack'), ('40_D', 'Delivering'), ('50_F', 'Finished')], db_index=True, default='N', max_length=5, verbose_name='статус'),
        ),
    ]
