# Generated by Django 3.2.15 on 2024-01-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20240111_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('D', 'Наличными при доставке'), ('B', 'Накопленными бонусами/скидками'), ('O', 'Картой онлайн')], db_index=True, max_length=2, verbose_name='Способ оплаты'),
        ),
    ]
